
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install
      - run: npm t
      - run: npm install
      - run: npm run prod

